#+TITLE: Emacs Configuration
#+AUTHOR: Parikshit Machwe
#+STARTUP: outline
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./style.css">

* Introduction

The previous configuration was developed a couple of years back but in
the meantime a lot of packages have been updated and new replacements
have been created. Hence, this is an attempt to clean-up the previous
configuration.

The overall setup still remains the same. It uses the Jon Weigley's ubiqutous
[[https://github.com/jwiegley/use-package][use-package]] used all around by the Emacs community. Also this uses
/org-babel/ mode which is a fantastic package promoting [[https://www.youtube.com/watch?v=dljNabciEGg][Literate
Programming]].

* Bootstrap

Setup package repositories and =use-package=. Also, setup key-chords
along with key-bindings for the heavily used packages. Upgrading, to
=delight= from =diminish= package as =delight= provides more options
and is also integrated with =use-package=.

#+BEGIN_SRC emacs-lisp

  (require 'package)
  (setq package-archives '(("gnu"   . "http://elpa.gnu.org/packages/")
                           ("melpa" . "http://melpa.org/packages/")
                           ("org"   . "http://orgmode.org/elpa/")))
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package)
    (package-install 'bind-key))

  (eval-when-compile
    (require 'use-package)
    (require 'bind-key))

  (use-package-chords)
  (setq use-package-always-ensure t)

  (use-package delight)

#+END_SRC


* Basics

These are certain basic settings to reduce clutter and setup some
simple defaults.

+ The most notable is the =winner-mode= which does undo/redo for
  windows config are:

|-------------+-------------|
| Key binding | Function    |
|-------------+-------------|
| C-<left>    | winner-undo |
| C-<right>   | winner-redo |
|-------------+-------------|

#+BEGIN_SRC emacs-lisp

  (use-package emacs
    :config
    (menu-bar-mode -1)
    (tool-bar-mode -1)
    (scroll-bar-mode -1)
    (tooltip-mode -1)

    (setq inhibit-startup-message t)
    (setq initial-scratch-message "")

    (setq custom-file (concat user-emacs-directory "/custom.el"))
    (load custom-file 'noerror)

    ;; Keep all backup and auto-save files in one directory
    (setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
    (setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
    (setq delete-old-versions t
          kept-new-versions 6
          kept-old-versions 2
          version-control t)

    ;; UTF-8 please
    (setq locale-coding-system 'utf-8)   ; pretty
    (set-terminal-coding-system 'utf-8)  ; pretty
    (set-keyboard-coding-system 'utf-8)  ; pretty
    (set-selection-coding-system 'utf-8) ; please
    (prefer-coding-system 'utf-8)        ; with sugar on top

    ;; Turn off the blinking cursor
    (blink-cursor-mode -1)

    (setq-default indent-tabs-mode nil)
    (setq-default indicate-empty-lines t)

    ;; delete the region when typing, just like as we expect nowadays.
    (delete-selection-mode t)

    ;; -i gets alias definitions from .bash_profile
    (setq shell-command-switch "-ic")

    ;; show time
    (display-time)

    ;; winner mode to undo/redo window configurations
    (winner-mode 1)

    ;; always show the function
    (which-function-mode 1)

    ;; no bells please
    (defun my-bell-func()) ;; empty
    (setq ring-bell-function 'my-bell-func)
    (setq visible-bell nil)

    ;; http://endlessparentheses.com/faster-pop-to-mark-command.html
    ;; Go up last positions using C-u C-SPC C-SPC
    ;; instead of C-u C-SPC C-u C-SPC
    (setq set-mark-command-repeat-pop t)

    ;; If same marks are saved in the ring, pop out the same ones
    (defun my/multi-pop-to-mark (orig-fun &rest args)
      "Call ORIG-FUN until the cursor moves.
    Try the repeated popping up to 10 times."
      (let ((p (point)))
        (dotimes (i 10)
          (when (= p (point))
            (apply orig-fun args)))))

    (advice-add 'pop-to-mark-command :around
                #'my/multi-pop-to-mark))

#+END_SRC


* Notes

With Emacs 25, a new shell opens up in another window messing up the
existing window configuration. The following advice fixes this.

https://stackoverflow.com/questions/40301732/m-x-shell-open-shell-in-other-windows

#+BEGIN_SRC emacs-lisp

  (use-package shell
    :config
    (defun shell-same-window-advice (orig-fn &optional buffer)
      "Advice to make `shell' reuse the current window.

  Intended as :around advice."
      (let* ((buffer-regexp
              (regexp-quote
               (cond ((bufferp buffer)  (buffer-name buffer))
                     ((stringp buffer)  buffer)
                     (:else             "*shell*"))))
             (display-buffer-alist
              (cons `(,buffer-regexp display-buffer-same-window)
                    display-buffer-alist)))
        (funcall orig-fn buffer)))

    (advice-add 'shell :around #'shell-same-window-advice))
#+END_SRC

